name: pawpal
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ^3.6.0-131.0.dev

dependencies:
  cupertino_icons: ^1.0.8
  firebase_auth: 5.3.1
  firebase_core: 3.6.0
  flutter:
    sdk: flutter
  get: 4.6.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
