name: pawpal
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ^3.6.0-131.0.dev

dependencies:
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.8
  firebase_auth: 5.3.1
  firebase_core: 3.6.0
  firebase_storage: ^12.3.4
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6
  supabase_flutter: ^2.8.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
